### ISSUE TITLE
Wrong calculation

### ISSUE THREAD

**Issue by filips123** [os-js/osjs-calculator-application#1]
The calculator calculates the wrong answer. It displays that `3 + 3 * 3 = 18`, but this is incorrect. It is `3 + 3 * 3 = 3 + (3 * 3) = 12`.

Also, add support for other math operations like Brackets, Exponentiation, Square root... and other mathematics symbols from https://en.wikipedia.org/wiki/List_of_mathematical_symbols.

**Comment by andersevenrud** [comment]
I imagine there's a few more issues. I just lifted most of this from v2, so it needs some work :)

**Comment by andersevenrud** [comment]
Should be fixed now that it's using PEMDAS :blush:
